backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # Adjust as needed
public_folder: "/uploads"

collections:
  - name: "calendar"
    label: "Calendar"
    folder: "data"
    create: true
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Event", name: "event", widget: "string" }
