backend:
  name: github  # Or GitLab if you're using GitLab
  repo: your-github-username/your-repository  # Replace with your GitHub repo
  branch: main  # This is the branch to use for CMS

media_folder: "static/img"  # Folder where media files will be stored
public_folder: "/img"  # Public URL to access the media files

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"  # The folder where your content will be stored
    create: true  # Allow creating new blog posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # URL format for posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
